language:
  - objective-c

env:
  global:
    - VERSION="3.5.3"

# Default OSX (xcode image) is 10.11 (xcode 7.3.1) as of 2017-05-02
# See: https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version

matrix:
  include:
      - env: VERSION="2.7.13"
      - env: VERSION="3.4.4"
      - env: VERSION="3.6.1"
      # OS X 10.9
      - osx_image: beta-xcode6.1
      # Xcode 9.1 OS X 10.12
      - osx_image: xcode9.1
      # Xcode 8.3.2 OS X 10.12
      - osx_image: xcode8.3
      # Xcode 8gm OS X 10.11
      - osx_image: xcode8
      # Default Xcode 7.3.1 OS X 10.11
      - osx_image: xcode7.3
      # Xcode 6.4 OS X 10.10
      - osx_image: xcode6.4
      - env:
          - VERSION=2.7.13
          - BUILD_WHEELS=1

install:
  - set -vx  # echo commands
  - source multibuild/osx_utils.sh
  - get_macpython_environment $VERSION venv
  - pip install wheel nose
  - if [ -n "$BUILD_WHEELS" ]; then
        pip install cython;
        (cd wheel_makers && ./make_wheels.sh);
    fi
  - pip install .

script:
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - nosetests delocate
